# Generated by Django 4.0.1 on 2022-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template', models.TextField()),
                ('email_recipients', models.CharField(max_length=1000)),
                ('email_status', models.SmallIntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers_email_notification',
                'managed': False,
            },
        ),
    ]
