# Generated by Django 4.0.1 on 2022-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhonesReestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_description', models.CharField(max_length=100)),
                ('phone_numbers', models.CharField(max_length=10, unique=True)),
                ('determinant_status', models.CharField(max_length=100)),
                ('determinant_verdict', models.CharField(max_length=100)),
                ('determinant_polarity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phones_reestr',
            },
        ),
    ]
