# Generated by Django 4.0.1 on 2022-01-29 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0003_alter_phonesreestr_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='determinant_polarity',
            new_name='det_polarity',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='determinant_status',
            new_name='det_status',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='determinant_verdict',
            new_name='det_verdict',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='phone_description',
            new_name='phone_desc',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='ts',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='phonesreestr',
            name='time_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 13, 44, 10, 692868, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
