# Generated by Django 4.0.1 on 2022-01-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0004_rename_determinant_polarity_phonesreestr_det_polarity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='phone_numbers',
            new_name='phone_nums',
        ),
    ]
