# Generated by Django 4.0.1 on 2022-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0005_rename_phone_numbers_phonesreestr_phone_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesreestr',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
