# Generated by Django 4.0.1 on 2022-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0006_alter_phonesreestr_time_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='det_polarity',
            new_name='det_polar',
        ),
        migrations.AlterField(
            model_name='phonesreestr',
            name='phone_nums',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
