# Generated by Django 4.0.1 on 2022-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0007_rename_det_polarity_phonesreestr_det_polar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesreestr',
            name='det_polar',
            field=models.CharField(default='check_need', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonesreestr',
            name='det_status',
            field=models.CharField(default='check_need', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonesreestr',
            name='det_verdict',
            field=models.CharField(default='check_need', max_length=100),
        ),
    ]
