# Generated by Django 4.0.1 on 2022-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0008_alter_phonesreestr_det_polar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesreestr',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phonesreestr',
            name='time_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
