# Generated by Django 4.0.1 on 2022-01-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0010_rename_time_created_phonesreestr_time_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='time_update',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='time_create',
            new_name='time_updated',
        ),
    ]
