# Generated by Django 4.0.1 on 2022-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0011_rename_time_update_phonesreestr_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesreestr',
            name='need_to_update',
            field=models.SmallIntegerField(default=1),
        ),
    ]
