# Generated by Django 4.0.1 on 2022-01-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0012_phonesreestr_need_to_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesreestr',
            name='det_desc',
            field=models.CharField(default='check_need', max_length=100),
        ),
    ]
