# Generated by Django 4.0.1 on 2022-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0013_phonesreestr_det_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesreestr',
            name='need_to_improve',
            field=models.SmallIntegerField(default=0),
        ),
    ]
