# Generated by Django 4.0.1 on 2022-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0014_phonesreestr_need_to_improve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonesreestr',
            name='need_to_improve',
        ),
    ]
