# Generated by Django 4.0.1 on 2022-01-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0015_remove_phonesreestr_need_to_improve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='det_polar',
            new_name='state',
        ),
    ]
