# Generated by Django 4.0.1 on 2022-01-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0016_rename_det_polar_phonesreestr_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='state',
            new_name='phone_state',
        ),
    ]
