# Generated by Django 4.0.1 on 2022-01-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_resurrection', '0017_rename_state_phonesreestr_phone_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='det_desc',
            new_name='phone_descr',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='phone_nums',
            new_name='phone_numbs',
        ),
        migrations.RenameField(
            model_name='phonesreestr',
            old_name='need_to_update',
            new_name='update_need',
        ),
        migrations.RemoveField(
            model_name='phonesreestr',
            name='det_status',
        ),
        migrations.RemoveField(
            model_name='phonesreestr',
            name='det_verdict',
        ),
        migrations.RemoveField(
            model_name='phonesreestr',
            name='phone_desc',
        ),
    ]
